name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Restore
        working-directory: src/Solution
        run: dotnet restore JRPG.sln

      - name: Build
        working-directory: src/Solution
        run: dotnet build JRPG.sln --configuration Release --no-restore

      - name: Test
        working-directory: src/Solution
        run: dotnet test JRPG.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx" --logger "console;verbosity=normal"

      - name: Show Results
        working-directory: src/Solution
        run: cat JRPG.Services.Tests/TestResults/test_results.trx
